{% set name = "tidypolars" %}
{% set version = "0.2.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tidypolars-{{ version }}.tar.gz
  sha256: b082916ced59e995e4f6947cc8c24ea949804e38f5cca4f90a0c61da506c2442

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6,<3.11
    - pip
    - poetry
  run:
    - python >=3.6,<3.11
    - polars >=0.14.0

test:
  imports:
    - tidypolars
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/tidypolars/
  summary: Tidy interface to polars
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - markfairbanks
    - nsandau
