{% set name = "tidypolars" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tidypolars-{{ version }}.tar.gz
  sha256: 009cb92d3211fb20a375adbfcf043703b04411aa22c05351addd13addff84f67

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6,<3.11
    - pip
    - poetry
  run:
    - python >=3.6,<3.11
    - polars >=0.14.18

test:
  imports:
    - tidypolars
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/tidypolars/
  summary: Tidy interface to polars
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - markfairbanks
    - nsandau
